export const DEVICE_SCREEN = 'DEVICE_SCREEN';

export const REQUEST_LOADING = 'REQUEST_LOADING';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const PHONE_LIST_LOADING = 'PHONE_LIST_LOADING';
export const PHONE_LIST_ERROR = 'PHONE_LIST_ERROR';
export const PHONE_LIST_SUCCESS = 'PHONE_LIST_SUCCESS';
export const PHONE_LIST_STATE = 'PHONE_LIST_STATE'
export const PHONE_ITEM_SUCCESS = 'PHONE_ITEM_SUCCESS'

export const PHONE_HOT_PRICE_LOADING = 'PHONE_HOT_PRICE_LOADING';
export const PHONE_HOT_PRICE_ERROR = 'PHONE_HOT_PRICE_ERROR';
export const PHONE_HOT_PRICE_SUCCESS = 'PHONE_HOT_PRICE_SUCCESS';

// export const ADD_FAVORITE_DEVICE = 'ADD_FAVORITE_DEVICE';
export const SET_FAVORITE_DEVICES = 'SET_FAVORITE_DEVICES';

