export const DEVICE_SCREEN = 'DEVICE_SCREEN';

export const REQUEST_LOADING = 'REQUEST_LOADING';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const PHONE_LIST_LOADING = 'PHONE_LIST_LOADING';
export const PHONE_LIST_ERROR = 'PHONE_LIST_ERROR';
export const PHONE_LIST_SUCCESS = 'PHONE_LIST_SUCCESS';
export const PHONE_LIST_STATE = 'PHONE_LIST_STATE'
export const PHONE_ITEM_SUCCESS = 'PHONE_ITEM_SUCCESS'

export const TABLET_LIST_LOADING = 'TABLET_LIST_LOADING'
export const TABLET_LIST_SUCCESS = 'TABLET_LIST_SUCCESS'
export const TABLET_LIST_ERROR = 'TABLET_LIST_ERROR'
export const TABLET_LIST_STATE = 'TABLET_LIST_STATE'
export const TABLET_ITEM_SUCCESS = 'TABLET_ITEM_SUCCESS'

export const SET_FAVORITE_DEVICES = 'SET_FAVORITE_DEVICES';

export const SET_CART_DEVICE_LIST = 'SET_CART_DEVICE_LIST'