export const DEVICE_SCREEN = 'DEVICE_SCREEN';

export const PHONE_LIST_LOADING = 'PHONE_LIST_LOADING';
export const PHONE_LIST_ERROR = 'PHONE_LIST_ERROR';
export const PHONE_LIST_SUCCESS = 'PHONE_LIST_SUCCESS';
export const PHONE_LIST_STATE = 'PHONE_LIST_STATE'
export const PHONE_ITEM_SUCCESS = 'PHONE_ITEM_SUCCESS'